"""updated product table

Revision ID: 47f18b078043
Revises: f433180e847d
Create Date: 2023-09-19 09:48:14.403447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47f18b078043'
down_revision = 'f433180e847d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.drop_column('quanity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quanity', sa.INTEGER(), nullable=False))
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
